repos:
  - repo: https://github.com/tanx-libs/precommit-hooks
    rev: v1.1.4 # please check the latest release, under releases
    hooks:
      - id: private_key_check # checkout all hooks under .pre-commit-hooks.yaml
